include ../makefile.include	
CFLAGS=-I..

all: test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 test12 test13 test14 test15 test16 test17 test18 test19 test20 test21 test22 test23 test24 test25 test26  test27 test28 test29 test30 test31 test32 test33 test34 test34 test35 test36 test37 test38 test39 test40 test41 test42 test43 test44 test45 test46 test47 test48 test49 test50 test51 test52 test53
 
test: runtest1 runtest2 runtest3 runtest4 runtest5 runtest6 runtest7 runtest8 runtest9 runtest10 runtest11 runtest12 test13 runtest14 runtest15 runtest16 runtest17 runtest18 runtest19 runtest20 runtest21 runtest2 runtest23 runtest24 runtest25 runtest26 runtest27 runtest28  runtest29 runtest30 runtest31 runtest32 runtest33 runtest34 runtest35 runtest36 runtest37 runtest38 runtest39 runtest40 runtest41 runtest42 runtest43 runtest44 runtest45 runtest46 runtest47 runtest48 runtest49 runtest50 runtest51 runtest52 runtest53

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules


RELPATH_VFOBJ = $(VFOBJ:%=../%)
test1: test1.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o test1 test1.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test2: test2.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o test2 test2.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test3: test3.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o test3 test3.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test4: test4.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o test4 test4.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test5: test5.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test6a: test6a.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test6: test6.o ${RELPATH_VFOBJ} chkopts
	${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}
	#@echo PETSC_LIB is ${PETSC_LIB}
	#@echo PETSC_TAO_LIB is ${PETSC_TAO_LIB}

test7: test7.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test8: test8.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test9: test9.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test10: test10.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test11: test11.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test12: test12.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test13: test13.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test14: test14.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test15: test15.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test16: test16.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test16_sym: test16_sym.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}
	
test17: test17.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test18: test18.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test19: test19.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test20: test20.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test21: test21.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}
	
test22: test22.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test23: test23.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test24: test24.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test25: test25.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test26: test26.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test27: test27.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test28: test28.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test29: test29.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test30: test30.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test31: test31.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test32: test32.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test33: test33.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test34: test34.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test35: test35.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test36: test36.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test37: test37.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test38: test38.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test39: test39.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test40: test40.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test41: test41.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test42: test42.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test43: test43.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}
	
test44: test44.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test45: test45.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test46: test46.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test47: test47.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test48: test48.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test49: test49.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test50: test50.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test51: test51.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

test52: test52.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}
	
test53: test53.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}

temp: temp.o ${RELPATH_VFOBJ} chkopts
	-@${CLINKER} -o $@ $@.o ${RELPATH_VFOBJ} ${PETSC_TAO_LIB}
	
runtest1: test1
	@echo "Running " $@
	-@ARGS=' -n 201,2,2 -l 10,1,1 -orientation 0 -nu 0 -epsilon 0.25 -eta 0 -gc .1 -maxtimestep 11 -maxtimevalue 4 -atnum 1';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then echo "\t$< succeeded\n========================================="; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest2: test2
	@echo "Running " $@
	-@ARGS='-n 41,81,6 -l 1,2,.25 -length .4 -orientation 3 -nu 0 -epsilon 0.05 -eta 1e-8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then echo "\t$< succeeded\n========================================="; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest2-large: test2
	@echo "Running " $@
	-@ARGS='-n 161,321,6 -l 4,8,.25 -length .4 -orientation 3 -nu 0 -epsilon 0.05 -eta 1e-8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 4 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then echo "\t$< succeeded\n========================================="; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest3: test3
	@echo "Running" $@
	-@ARGS='-n 41,41,6 -l 2,2,.25 -length .4 -orientation 1 -nu 0 -eta 1e-8' ;\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then echo "\t$< succeeded\n========================================="; \
	else echo ${PWD} ; echo "\tPossible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest4: test4
	@echo "Running " $@
	-@ARGS='-n 81,81,6 -l 2,2,.25 -length .4 -orientation 3 -nu 0 -epsilon ${EPSILON} -eta 1e-8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then echo "\t$< succeeded\n========================================="; \
	else echo ${PWD} ; echo "\tPossible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest5: test5
	@echo "Running " $@
	-@for or in 0 1 2 3 4 5; do \
	ARGS="-n 21,21,21 -l 1,1,1 -nu 0 -epsilon .05 -eta 1e-8 -orientation $$or";\
	echo "Running " ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@-$$or ;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@-$$or | grep -v -e '      \#' > $@-$$or.out 2>&1;\
	if (${DIFF} -B results/$@-$$or.out $@-$$or.out) then echo "\t$<-$$or succeeded\n========================================="; \
	else echo ${PWD} ; echo "\tPossible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@-$$or.out;\
	done

runtest6: test6
	@echo "Running " $@
	-@for or in 0 1 2; do \
	ARGS="-n 21,21,21 -l 1,1,1 -nu 0.3 -orientation $$or";\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@-$$or;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@-$$or | grep -v -e '      \#' > $@-$$or.out 2>&1;\
	if (${DIFF} -B results/$@-$$or.out $@-$$or.out) then echo "\t$<-$$or succeeded\n========================================="; \
	else echo ${PWD} ; echo "\tPossible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@-$$or.out;\
	done
	
runtest7: test7
	@echo "Running " $@
	-@for or in 0 1 2; do \
	ARGS="-n 21,21,21 -l 1,1,1 -nu 0.3 -orientation $$or";\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@-$$or | grep -v -e '      \#' > $@-$$or.out 2>&1;\
	if (${DIFF} -B  results/$@-$$or.out $@-$$or.out) then echo "\t$<-$$or succeeded\n========================================="; \
	else echo ${PWD} ; echo "\tPossible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@-$$or.out;\
	done

runtest8: test8
	@echo "Running " $@
	-@ARGS='-n 41,41,81 -l 1,1,2 -radius .75 -orientation 3 -nu 0 -epsilon 0.05 -eta 1e-8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest8-large: test8
	@echo "Running " $@
	-@ARGS='-n 81,81,161 -l 1,1,2 -radius .75 -orientation 3 -nu 0.3 -epsilon 0.025 -eta 1e-8';\
	echo ${MPIEXEC} -n 8 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest9: test9
	@echo "Running " $@
	-@ARGS='-n 51,2,51 -l 4,0.01,4 -epsilon .16 -npc 1 -pc0_center 2,.005,2 -pc0_r .2 -pc0_theta 0 -pc0_phi 45 -pc0_thickness 0.2 -pc0_name -orientation 2';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest10: test10
	@echo "Running " $@
	-@for or in 0; do \
	-@ARGS='-n 51,2,51 -l 4,0.01,4 -epsilon .16 -npc 1 -pc0_center 2,.005,2 -pc0_r .2 -pc0_theta 0 -pc0_phi 45 -pc0_thickness 0.2 -pc0_name -orientation 2';\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@-$$or | grep -v -e '      \#' > $@-$$or.out 2>&1;\
	if (${DIFF} -B  results/$@-$$or.out $@-$$or.out) then echo "\t$<-$$or succeeded\n========================================="; \
	else echo ${PWD} ; echo "\tPossible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@-$$or.out;\
	done

runtest11: test11
	@echo "Running " $@
	-@ARGS='-n 41,41,6 -l 2,2,.25 -length .4 -nu 0 -epsilon .05 -eta 1e-8 -pinc 1e-6 -maxtimestep 1000 -Gc 4.e-9';\
	echo ${MPIEXEC} -n 8 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 8 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "\tPossible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@-$$or.out;\

runtest12: test12
	@echo "Running " $@
	-@ARGS='-n 21,21,21 -l 1,1,1 -height .1 -length .1 -orientation 1 -nu 0 -epsilon 0.05 -eta 1e-8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest13: test13
	@echo "Running " $@
	-@ARGS='-n 21,21,21 -l 1,1,1 -length .4 -orientation 1 -nu 0 -epsilon 0.05 -eta 1e-8';\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ > $@.out 2>&1;\
	if (${DIFF} -I '^#' results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest14: test14
	@echo "Running " $@
	-@ARGS='-n 21,21,21 -l 1,1,1 -height .1 -length .1 -orientation 1 -nu 0 -epsilon 0.05 -eta 1e-8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest15: test15
	@echo "Running " $@
	-@ARGS='-n 21,21,21 -l 1,1,1 -height .1 -length .1 -orientation 1 -nu 0 -epsilon 0.05 -eta 1e-8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest16: test16
	@echo "Running " $@
	-@ARGS='-options_file test16.opts';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest17: test17
	@echo "Running " $@
	-@ARGS='-n 21,21,21 -l 1,1,1 -length 1. -length1 .5 -orientation 2 -nu 0 -epsilon 0.05 -eta 1e-8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest18: test18
	@echo "Running " $@
	-@ARGS='-n 41,41,41 -l 4,4,4 -epsilon .2 -npc 1 -pc0_center 2,2,2 -pc0_r .2 -pc0_theta 0 -pc0_phi 45 -pc0_thickness 0.2 -pc0_name -orientation 2';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest19: test19
	@echo "Running " $@
	-@for or in 0; do \
	ARGS="-n 21,21,21 -l 1,1,1 -nu 0.3 -length .2 -orientation $$or";\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@-$$or | grep -v -e '      \#' > $@-$$or.out 2>&1;\
	if (${DIFF} -B  results/$@-$$or.out $@-$$or.out) then echo "\t$<-$$or succeeded\n========================================="; \
	else echo ${PWD} ; echo "\tPossible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@-$$or.out;\
	done

runtest20: test20
	@echo "Running " $@
	-@for or in 0; do \
	ARGS="-n 21,21,21 -l 1,1,1 -nu 0.3 -length .2 -orientation $$or";\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@-$$or | grep -v -e '      \#' > $@-$$or.out 2>&1;\
	if (${DIFF} -B  results/$@-$$or.out $@-$$or.out) then echo "\t$<-$$or succeeded\n========================================="; \
	else echo ${PWD} ; echo "\tPossible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@-$$or.out;\
	done

runtest21: test21
	@echo "Running " $@
	-@for or in 0; do \
	ARGS="-n 21,21,21 -l 1,1,1 -nu 0.3 -length .2 -orientation $$or";\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@-$$or | grep -v -e '      \#' > $@-$$or.out 2>&1;\
	if (${DIFF} -B  results/$@-$$or.out $@-$$or.out) then echo "\t$<-$$or succeeded\n========================================="; \
	else echo ${PWD} ; echo "\tPossible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@-$$or.out;\
	done

runtest23: test23
	@echo "Running " $@
	-@for or in 0; do \
	ARGS="-n 21,21,21 -l 1,1,1 -nu 0.3 -length .2 -orientation $$or";\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@-$$or | grep -v -e '      \#' > $@-$$or.out 2>&1;\
	if (${DIFF} -B  results/$@-$$or.out $@-$$or.out) then echo "\t$<-$$or succeeded\n========================================="; \
	else echo ${PWD} ; echo "\tPossible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@-$$or.out;\
	done

runtest24: test24
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0 -velp_pc_type jacobi';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then echo "\t$< succeeded\n========================================="; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out


runtest25: test25
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0 -velp_pc_type jacobi';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest26: test26
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0 -velp_pc_type jacobi';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest27: test27
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0 -velp_pc_type jacobi';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest28: test28
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest29: test29
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest30: test30
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest31: test31
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest32: test32
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest33: test33
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest34: test34
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest35: test35
	@echo "Running " $@
	-@ARGS='-n 11,11,11 -l 1.,1.,1. -m_inv 0';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest36: test36
	@echo "Running " $@
	-@ARGS='-n 11,11,2 -l 1.,1.,0.01 -m_inv 0';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest37: test37
	@echo "Running " $@
	-@ARGS='-n 11,11,2 -l 1.,1.,0.01 -m_inv 1';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest38: test38
	@echo "Running " $@
	-@ARGS='-n 11,11,2 -l 1.,1.,0.01 -m_inv 1';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest39: test39
	@echo "Running " $@
	-@ARGS='-n 11,11,2 -l 1.,1.,0.01 -m_inv 1';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest40: test40
	@echo "Running " $@
	-@ARGS='-n 11,11,2 -l 1.,1.,0.01 -m_inv 0';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest41: test41
	@echo "Running " $@
	-@ARGS='-n 11,11,2 -l 1.,1.,0.01 -m_inv 0';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest42: test42
	@echo "Running " $@
	-@ARGS='-n 21,5,2 -l 1.,0.4,0.01';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest43: test43
	@echo "Running " $@
	-@ARGS='-n 21,5,2 -l 1.,0.4,0.01';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out
runtest44: test44
	@echo "Running " $@
	-@ARGS='-n 21,5,2 -l 1.,0.4,0.01';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
runtest46: test46
	@echo "Running " $@
	-@ARGS='-n 21,21,2 -l 1.,1,0.01 -theta 1 -timestep 0.05 -maxtimestep 150 -cond 0.01';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out
runtest47: test47
	@echo "Running " $@
	-@ARGS='-n 21,21,2 -l 1.,1,0.01 -theta 1 -timestep 0.05 -maxtimestep 150 -condx 0.01 -condy 0.01 -velx 0.8 -vely 0.8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out
runtest48: test48
	@echo "Running " $@
	-@ARGS='-n 21,21,2 -l 1.,1,0.01 -theta 1 -timestep 0.05 -maxtimestep 150 -condx 0.01 -condy 0.01 -velx 0.8 -vely 0.8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out
runtest49: test49
	@echo "Running " $@
	-@ARGS='-n 21,21,2 -l 1.,1,0.01 -theta 1 -timestep 0.05 -maxtimestep 150 -condx 0.01 -condy 0.01 -velx 0.8 -vely 0.8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out
runtest50: test50
	@echo "Running " $@
	-@ARGS='-n 21,21,2 -l 1.,1,0.01 -theta 1 -timestep 0.05 -maxtimestep 150 -condx 0.01 -condy 0.01 -velx 0.8 -vely 0.8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out
runtest51: test51
	@echo "Running " $@
	-@ARGS='-n 21,21,2 -l 1.,1,0.01 -theta 1 -timestep 0.05 -maxtimestep 150 -condx 0.01 -condy 0.01 -velx 0.8 -vely 0.8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out
runtest52: test52
	@echo "Running " $@
	-@ARGS='-n 21,21,2 -l 1.,1,0.01 -theta 1 -timestep 0.05 -maxtimestep 150 -condx 0.01 -condy 0.01 -velx 0.8 -vely 0.8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

runtest53: test53
	@echo "Running " $@
	-@ARGS='-n 21,21,2 -l 1.,1,0.01 -theta 1 -timestep 0.05 -maxtimestep 150 -condx 0.01 -condy 0.01 -velx 0.8 -vely 0.8';\
	echo ${MPIEXEC} -n 2 ./$< $${ARGS} -p $@;\
	${MPIEXEC} -n 2 ./$< $${ARGS} -p $@ | grep -v -e '      \#' > $@.out 2>&1;\
	if (${DIFF} -B results/$@.out $@.out) then true; \
	else echo ${PWD} ; echo "Possible problem with with $<, diffs above \n========================================="; fi;\
	${RM} -f $@.out

clean::
	-rm -f test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 test12 test13 test14 test15 test16 test17 test18 test19 test20 test21 test22 test23 test24 test25 test26 test27 test28 test29 test30 test31 test32 test33 test34 test35 test36 test37 test38 test39 test40 test41 test42 test43 test44 test46 test47 test48 test49 test50 test51 test52 test53
	-rm -f runtest*
	-rm -f TEST*
